os: Visual Studio 2019

build_script:
 - cmd: dotnet tool install --global paket
 - cmd: dotnet restore src\RavenDB.DistributedCache\RavenDB.DistributedCache.fsproj
 - cmd: dotnet build -v n src\RavenDB.DistributedCache\RavenDB.DistributedCache.fsproj
 - cmd: dotnet pack src\RavenDB.DistributedCache\RavenDB.DistributedCache.fsproj -o %CD%\artifacts\nupkg
 
artifacts:
 - path: artifacts\nupkg\*.nupkg 

test: off
